### ISSUE TITLE
A bug of git clone command line in homepage

### ISSUE THREAD

**Issue by tossense** [sinatra/sinatra-recipes#123] opened 2015-11-26 15:51 UTC
in http://recipes.sinatrarb.com/
git clone git://github.com/sinatra/sinatra-recipes.git
should be:
git clone git@github.com:sinatra/sinatra-recipes.git

**Comment by kgrz** [comment] 2015-11-26 17:14
This is not a bug. `git://`, the Git protocol is a protocol that Github supports. This is analogous to `http://` or  `https://` protocol, but with some key differences. You can read about more about them [here](https://gist.github.com/grawity/4392747)

TL;DR, this is a way for public repos to be cloned without the user getting authenticated. When you use a `https://` URL, Github prompts for username + password combination to authenticate you before it starts the cloning. For `ssh`, you need a public key setup with Github.

Any reason that I'm missing about using (or not using) `git://`?

**Comment by tossense** [comment] 2015-11-27 02:31
Thanks for your kindly response. I've tried git:// at another computer, and it works :)
Sorry for this issue.

**Comment by kgrz** [comment] 2015-11-27 05:00
Closing this, then

**Closed by kgrz** 2015-11-27 05:00 UTC
